### ISSUE TITLE
It does not work with angular 8.0.0 and ivy enabled

### ISSUE THREAD

**Issue by sysmat** [rnadler/ng2-password-strength-bar#25]
when building I get error:

`ERROR in node_modules/ng2-password-strength-bar/lib/passwordStrengthBar.module.d.ts(1,22): error TS-996002`

**Comment by jhkueh** [comment]
Any chance of updating the library to support Angular 9? Or do you accept PR?

**Comment by rnadler** [comment]
@jhkueh I'm not sure how backward compatibility would work, but I'd be happy to evaluate a PR. Thanks!

**Comment by rnadler** [comment]
Please see https://github.com/rnadler/ng2-password-strength-bar/issues/26#issuecomment-640323525.
